### ISSUE TITLE
[BUG] Error when snowpack tries to access a sass/scss file

### ISSUE THREAD

**Issue by N0tExisting** [N0tExisting/Snowpack-Js-Sass#1]
### Whenever snowpack tries to access a sass/scss file the following error is thrown:
```
[20:23:46] [snowpack] Build Result Error: There was a problem with a file build result.
[20:23:46] [snowpack] TypeError: Cannot read property 'readFile' of undefined
    at Object.load (G:\Libraries\Repos\Sass-Plugin\out\index.js:140:30)
    at runPipelineLoadStep (G:\Libraries\Repos\Sass-Plugin\testFixture\node_modules\snowpack\lib\index.js:122543:43)
    at Object.buildFile (G:\Libraries\Repos\Sass-Plugin\testFixture\node_modules\snowpack\lib\index.js:122742:30)
    at G:\Libraries\Repos\Sass-Plugin\testFixture\node_modules\snowpack\lib\index.js:163417:57
    at FileBuilder.build (G:\Libraries\Repos\Sass-Plugin\testFixture\node_modules\snowpack\lib\index.js:163425:11)
    at loadUrl (G:\Libraries\Repos\Sass-Plugin\testFixture\node_modules\snowpack\lib\index.js:182834:37)
    at handleRequest (G:\Libraries\Repos\Sass-Plugin\testFixture\node_modules\snowpack\lib\index.js:182937:34)
    at Server.<anonymous> (G:\Libraries\Repos\Sass-Plugin\testFixture\node_modules\snowpack\lib\index.js:182986:13)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17) {
  __snowpackBuildDetails: { name: 'Js-Sass', step: 'load' }
}
[20:23:46] [snowpack] TypeError: Cannot read property 'readFile' of undefined
```
#### **TODO:** Figure Out Logging

**Comment by N0tExisting** [comment]
This seems to be an issue with snowpack using a diffrent property than the types say. _**[See also](https://github.com/snowpackjs/snowpack/blob/main/plugins/plugin-postcss/plugin.js#L63)**_
